version: "2.1"
services:
  spring-boot-localstack:
    build:
      context: .
    image: spring-boot-localstack
    mem_limit: 1024m
    ports:
      - "8090:8080"
  localstack:
   image: localstack/localstack:0.9.4
   container_name: localstack
   ports:
     - "4572-4572:4572-4572" # ports of the different services
     - "9000:9000"
   environment:
     - SERVICES=s3 # a list of desired services you want to use.
     - DEFAULT_REGION=eu-west-1 # This is the region where your localstack mocks to be running
     - DATA_DIR=/tmp/localstack/data
     - PORT_WEB_UI=9000
     - LAMBDA_EXECUTOR=local
     - DOCKER_HOST=unix:///var/run/docker.sock
     - START_WEB=1
     - DEBUG=1